$(document).ready(() => {
  const $body = $('body');
  const $tweetsDiv = $('<div id="tweets">');
  $body.append($tweetsDiv);

  // Create a button to show new tweets
  const $showNewTweetsButton = $('<button>Show New Tweets</button>');
  $body.prepend($showNewTweetsButton); // Add the button at the beginning of the body

  function makeNewTweets() {
    // Clear the existing tweets
    $tweetsDiv.html('');

    // Iterate through the latest tweets in reverse order to display new tweets at the top
    for (let i = streams.home.length - 1; i >= 0; i--) {
      const tweet = streams.home[i];
      const $tweet = $('<div></div>');
      const text = `@${tweet.user}: ${tweet.message}`;
      $tweet.text(text);
      $tweetsDiv.append($tweet);
    }
  }

  function handleNewTweet(tweet) {
    // Append the new tweet to the top of the tweets div
    const $newTweet = $('<div></div>');
    const newText = `@${tweet.user}: ${tweet.message}`;
    $newTweet.text(newText);
    $tweetsDiv.prepend($newTweet);
  }

  // Initial rendering of tweets
  makeNewTweets();

  // Function to handle new tweets generated by the data generator
  function handleNewTweetFromGenerator() {
    const latestTweet = streams.home[streams.home.length - 1];
    handleNewTweet(latestTweet);
  }

  // Bind a click event to the button
  $showNewTweetsButton.click(() => {
    handleNewTweetFromGenerator();
  });
});
