$(document).ready(() => {
  // $body set equal to the <body> element
  const $body = $('body');
  // make a new div element with the id "tweets" and assign it to $tweetsDiv
  const $tweetsDiv = $('<div id="tweets">');
  // add $tweetsDiv to body using append
  // child of body
  $body.append($tweetsDiv);
  // creates button element called "Show New Tweets" and assign it to $showNewTweetsButton
  const $showNewTweetsButton = $('<button>Show New Tweets</button>');
  // add $showNewTweets button to body using prepend
  // first child of body
  $body.prepend($showNewTweetsButton);

  // create a function to make new tweets
  function makeNewTweets() {
    // clear the existing tweets so new tweets replace the old ones
    $tweetsDiv.html('');
    // iterate through the latest tweets in reverse order to display new tweets at the top
    for (let i = streams.home.length - 1; i >= 0; i--) {
      // get all tweets in reverse order and assign it to tweet
      const tweet = streams.home[i];
      // create a new div and assign it to $tweet
      const $tweet = $('<div id="each tweet">');
      // timestamps
      const originalTimestamp = moment(tweet.created_at).format("MMMM Do YYYY, h:mm:ss a");
      const relativeTimestamp = moment(tweet.created_at).fromNow();
      // the text that shows up on my site
      const text = `${originalTimestamp}, @${tweet.user}: ${tweet.message} (${relativeTimestamp})`;
      // sets the text to $tweet
      $tweet.text(text);
      // add $tweet to $tweetsDiv using append
      $tweetsDiv.append($tweet);
    }
  }
  // create a function to add the new tweets to the top of the tweets div
  function handleNewTweet(tweet) {
    // create a new div and assign it to $newTweet
    const $newTweet = $('<div id="each new tweet">');
    // timestamp
    const originalTimestamp = moment(tweet.created_at).format("MMMM Do YYYY, h:mm:ss a");
    const relativeTimestamp = moment(tweet.created_at).fromNow();
    // the text that shows up on my site
    const newText = `${originalTimestamp}, @${tweet.user}: ${tweet.message} (${relativeTimestamp})`;
    // sets the text to $newTweet
    $newTweet.text(newText);
    // add $newTweet to $tweetsDiv using prepend (so the new tweets show up at the top)
    $tweetsDiv.prepend($newTweet);
  }
  // call original function so the original tweets show up
  makeNewTweets();
  // create a function to handle new tweets generated by the data generator
  function handleNewTweetFromGenerator() {
    // latestTweet = last element of the streams.home array
    // gets the latest tweet from the generator
    const latestTweet = streams.home[streams.home.length - 1];
    // call handleNewTweet using latestTweet so the new tweets show up first
    handleNewTweet(latestTweet);
  }
  // bind a click event to the button
  $showNewTweetsButton.click(() => {
    handleNewTweetFromGenerator();
  });
  // function to update timestamps periodically
  function updateTimestamps(){
    makeNewTweets();
  }
  // update timestamps every minute
  setInterval(updateTimestamps, 60000);
});
